### ISSUE TITLE
Hitting the Points at Infinite

### ISSUE THREAD

**Issue by iReynaldo** [UConnCompGeom/VisibilityPolygonJS#2]
## Summary

How to deal with these points that go out to infinite (related to [Remove Intersections](#1)).
Notice the points the reach the edge of the picture. How should we achieve this in our application?

![screenshot from 2016-11-16 18-17-26](https://cloud.githubusercontent.com/assets/4662358/20370323/202661ba-ac2c-11e6-950b-c3fa9960f999.png)

**Comment by BenGentzel** [comment]
Currently goes to infinite, but it is an all or nothing.  Either the ray goes through the vertex to the border or it stops at the vertex.  Cases where it goes through the vertex and then stops at an edge (see the left of the image on this issue where it passes a vertex and then hits the leftmost quadrilateral) currently stop at the vertex.  Fixing that is the next step for this issue.

**Comment by BenGentzel** [comment]
The test through half-intersects didn't work before.  It should work now.  Additionally a line through a vertex should now stop at the first edge.  There may currently be a bug when going through a vertex and then intersecting a vertex that it shouldn't pass through (I think it will keep going).
